/* GERADO — não editar à mão.
 *
 * Fonte: `dados/oficiais/ueln-bases.csv`. Para mudar, edita-se o CSV e
 * corre-se `npm run oficiais:gerar`. A proveniência está em
 * `dados/oficiais/README.md`. */

/**
 * As bases de dados e stud-books que emitem números UELN.
 *
 * Um UELN tem quinze caracteres em três blocos:
 *
 * ```
 *   620  003  004471234
 *   └┬┘  └┬┘  └───┬───┘
 *    │    │       └── 9 caracteres: o número do animal nessa base
 *    │    └────────── 3 caracteres: **o código desta lista**
 *    └─────────────── 3 algarismos: o país, ISO 3166-1 numérico
 * ```
 *
 * O `components/vender-cavalo/passaporte-ueln.ts` dizia por escrito que não
 * validava o bloco do meio «porque a lista é mantida pelos organismos do UELN
 * e não a temos; inventar quais são os válidos seria recusar passaportes reais
 * por causa de uma lista adivinhada». Agora temos a lista.
 *
 * **Mas a regra não muda: desconhecido é desconhecido, nunca inválido.** Esta
 * lista tem 720 códigos e não é garantidamente completa nem
 * eterna — organizações novas entram, e a cópia que temos é de um dia. Um
 * código que aqui não esteja pode ser de uma base que existe; recusá-lo seria
 * repetir, com uma lista a sério, exactamente o erro que se evitou quando não
 * havia lista nenhuma.
 */
export const BASES_UELN: Readonly<Record<string, string>> = {
  "012001": "Office National De Developpement Des Elevages Equins et camelins",
  "020001": "Govern d'Andorra Departament d'Agricultura",
  "031001": "Azerbaijan Horse Club",
  "031002": "Azerbaijan Republic Equestrian Federation",
  "032001": "Asociacion Argentina de Fomento Equino",
  "032002": "Sociedad Rural Argentina",
  "032003": "Stud-book Argentino",
  "036001": "Australian Warmblood Horse Association Ltd",
  "036002": "Holsteiner Horse Association of Australia Ltd",
  "036003": "Stud-book APH Australian Performances Horses",
  "036004": "The Arabian Horse Society of Autralia Ltd",
  "036005": "The Welsh Pony & Cob Society of Australia",
  "036006": "Australian Pony Stud Book Society",
  "036007": "Trakehner Kontaktadressen im Ausland",
  "036008": "Harness Racing Australia Inc",
  "036009": "Australian Lipizzaner Registry Inc",
  "036010": "Irish Draught and Sport Horse Society of Australia",
  "036011": "Asociacion de Caballos de Pura Raza Espanola - Australia INC",
  "036012": "Hanoverian Horse Society of Australia",
  "036013": "Australian Continental Equestrian Group Inc",
  "036014": "Lipizzaner Association of Australasia",
  "036015": "Australian Paso Horse Society of Australia",
  "036016": "Icelandic Horse Association of Australia Inc.",
  "036017": "Australian Fjord Horse Association Inc.",
  "036AUS": "Australian Stud Book",
  "040001": "Bundesgestüt Piber",
  "040002": "Burgenlädischer Pferdezuchtverband",
  "040003": "Haflinger Pferdezucht-verband Tirol",
  "040004": "Haflinger-Pferdezuchtverband Salzburg",
  "040005": "Landespferdezuchtverband Kärnten",
  "040006": "Landespferdezuchtverband Salzburg",
  "040007": "Landespferdezuchtverband Steiermark",
  "040008": "Zuchtverband Stadt-Paura",
  "040009": "Osterreichischer Araber zuchtverband",
  "040010": "Österreichischer Islandpferdezuchtverband",
  "040012": "Tiroler Noriker Pferdezuchtverband",
  "040013": "Verband der lipizzanerzüchter in Osterreich",
  "040014": "Verband der Pony und Kleinpferdezüchter in Osterreich",
  "040015": "Verband der VollblutAraber-Zuchter Osterreich",
  "040016": "Verband des Araber-Haflingerpferdes e V",
  "040017":
    "Verband niederöster-reichischer Pferdezüchter zur Förderung der Pferdezucht und des pferdeabsatzes",
  "040018": "Verein der Warmblutpferdezüchter des Landes Salzburg",
  "040019": "Verein der Warmblutpferdezüchter des Landes Tirol",
  "040020": "Voralberger Pferdezuchtverband",
  "040021": "Vorarlberger Haflinger-zuchtverein",
  "040022": "Zentrale Arbeitsgemeinschaft Osterreichischer Pferdezuchter",
  "040023": "Zentrale für traberzucht und rennen in Österreich",
  "040024": "Niederosterreichischer Islandpferdezuchtverband",
  "040025": "Verein der Voralberger Warmblutzuchter",
  "040026": "Verein der Voralberger Norikerzüchter",
  "040027": "Oesterreichischer Shetlandponyzuchtverband",
  "040028": "Osterreichische Lipizzaner Union",
  "040029": "Verband der Zuchter des Huzulenpferdes in Osterreich",
  "040030": "Austrian Quarter Horse Association",
  "040031": "Arbeitsgemeinschaft für Warmblutzucht in Österreich",
  "040032": "Österreichischer Pferdesportverband",
  "040033": "Amt der NO LReg. Abt. Veterinärangelegenheiten",
  "040034": "Amt der Burgenländischen Landesregierung Abteilung 4a - Hauptreferat Veterinärwesen",
  "040035": "Verband der Pferderassen und Ponys in Österreich",
  "040036": "Österreichischer Lipizzaner Zuchtverband - Austrian Breeding Federation",
  "040037": "Zuchtleitung Paint Horse Austria",
  "040038": "Paint Horse Austria",
  "040039": "International M'amin Horse Registry",
  "040AUT": "Direktorium für Galopprennsport und Vollblutzucht in Österreich",
  "048001": "Royal Arabian Stud of Bahrain",
  "048BHR": "Rashid Equestrian and Horse Racing Club",
  "052BRB": "Barbodo Stud Book",
  "056001": "Belgisch Arabisch Paardenstamboek vzw",
  "056002": "Belgisch Warmbloedpaard vzw",
  "056003": "Fédération belge des courses hippiques",
  "056004": "Association Belge des Eleveurs de Chevaux Lusitaniens",
  "056005": "Société Royale Le Cheval de Trait Ardennais",
  "056006": "Vlaamse Fokkers van het Belgisch Trekpaard",
  "056007": "Société royale le cheval de sport belge",
  "056008": "Stud-book Belge du Poney Fjord",
  "056009": "Stud-book Belge du Poney Haflinger",
  "056010": "Stud-book Belge du Cheval Islandais asbl",
  "056011": "Stud-book Belge du Poney New-Forest",
  "056012": "Stud-book Belge du Poney Shetland",
  "056013": "Stud-book Belge du Poney Welsh",
  "056014": "Le Lipizzan Belge",
  "056015": "Stud-book Zangersheide",
  "056016": "Belgian Highland Pony Society",
  "056017": "Royal Belgian Palomino",
  "056018": "Belgian Quarter Horse Association",
  "056019": "Association Belge du Cheval Barbe",
  "056020": "Association Wallonne des Eleveurs et Détenteurs d'Anes asbl",
  "056021": "Confédération Wallonie-Bruxelles du Cheval",
  "056022": "PaardenPunt Vlaanderen",
  "056023": "Belgische Ezel Vrieden",
  "056024": "Belgisch Merens Stamboek",
  "056025": "Belgian Connemara Pony Association",
  "056026": "Association Wallonne du Cheval de Trait belge",
  "056027": "Het Vlaams Paard",
  "056028": "Europese Arabo-Friezen Stamboek VZM",
  "056029": "Belgisch Stamboek van het Friese Paard - Studbook Belge du Cheval Frison",
  "056030": "Belgisch Stamboek van het Miniatuurpaard (SB Belge du cheval miniature)",
  "056031": "Irish Cob Society Belgie vzw",
  "056032": "Belgisch Tinker Stamboek vzw",
  "056033": "BELGIAN APPALOOSA",
  "056034": "Studbook Het Dressuurpaard",
  "056035": "Belgian Franches-Montagnes Association",
  "056036":
    "Société Royale Le Cheval de Trait Belge (Koninklijke Maatschapij Het Belgisch Trekpaard)",
  "056037": "KOEDBLOED KOEPEL vzw",
  "056BEL": "Vlaamse Federatie voor Paardenrennen",
  "068101": "Bolivian Association de Criadores de Caballos Arabes",
  "076001": "Associacao Brasileira de Criadores do Cavalo de Hipismo",
  "076002": "Associacao Brasileira de Criadores do cavalo Crioulo",
  "076003": "Associacao Brasileira de Criadores do Cavalo Quarto de Milha",
  "076004": "Associacao Brasileira dos criadores do cavalo Mangalarga Marchador",
  "076005": "Associacao Brasileira dos Criadores do cavalo Puro Sangre Lusitano",
  "076006": "Associacao Brasileira Dos Criadores Do Cavalo Arabe",
  "076007": "Associacao Brasileira dos criadores do cavalo da raca anglo-arabe",
  "076BRZ": "Stud Book Brasileiro do Cavalo de Corrida",
  "084001": "Belize Arabian Stud Book",
  "100001": "Bulgarian Horse Breeding Society",
  "100002": "national Service for selection and Reproduction in Animal Breeding",
  "100003": "National Veterinary Service",
  "100004": "Eastbulgarian Horse Association",
  "100005": "Association for Breeding Indigenous Breeds in Bulgaria",
  "100006": "Bulgarian Sport Horse Association",
  "112001": "Belarus Trotters",
  "124001": "Canadian Arabian Horse Registry",
  "124002": "Canadian Sport Horse Association",
  "124003": "Equestrian Canada",
  "124004": "Canadian Icelandic Horse Federation",
  "124005": "Standardbred Canada",
  "124008": "American Saddlebred Horse Association of Canada",
  "124009": "Société des Eleveurs de Chevaux Canadiens",
  "124010": "Clydesdale Horse Association of Canada",
  "124011": "Canadian Fjord Horse Association",
  "124012": "Canadian Hackney Society",
  "124013": "Canadian Haflinger Association",
  "124014": "Canadian Morgan Horse Association Inc.",
  "124015": "Miniature Horse Association of Canada",
  "124016": "Canadian Palomino Horse Association",
  "124017": "Canadian Percheron Association",
  "124018": "Peruvian Horse Association of Canada",
  "124019": "Canadian Pony Society",
  "124020": "Canadian Registry of the Tenessee Walking Horse",
  "124021": "Canadian Trakehner Horse Society",
  "124022": "Welsh Pony & Cob Society of Canada",
  "124023": "Canadian Warmblood Horse Breeders Association",
  "124024": "Appaloosa Horse Club of Canada",
  "124027": "Irish Draught Horse Society of Canada",
  "124031": "Friesian Horse Society Inc.",
  "124100": "General Stud & Herd Book",
  "124999": "Canadian Identification Project",
  "124CAN": "The Jockey Club of America",
  "152001": "Sociedad de Fomento Agricola de Temuco",
  "152CHI": "Stud-book de Chile",
  "156001": "China Horse Industry Association",
  "170001": "Assn. Colombiana de Criadores de Caballos Arabe",
  "170COL": "Jockey Club in Colombia",
  "188CRI": "Jockey Club in Costa Rica",
  "191002": "Croatian Agency for Agriculture and Food - Thoroughbred area",
  "191003": "Drzavna ergela Dakovo i Lipik / State Stud Farm Dakovo and Lipik",
  "191004":
    "Hrvatska udruga uzgajivaca sportskih konja / Croatian Association of Breeders of Sport Horses",
  "191005": "Croatian Federation of Heavy Draft Horse Breeders Association",
  "191006": "Central Horsebreeders Alliance Croatian Posavac",
  "191007": "Trakehner Horse Breeders Association of Croatia",
  "191009": "Croatian Breeders Association of Gidran Horses",
  "191010": "Croatian Warmblood Breeders Association",
  "191011": "Vitesko alkarsko drustvo Sinj",
  "192001": "Associacion Nacional de Criadores de Equins de Cuba",
  "196CYP": "Cyprus Turf Club",
  "203001": "Czech Association of Horse Breeder Syndicates",
  "203002": "Association of hucul horse breeders",
  "203003": "Czech Association Purebred Arabian Horses",
  "203004": "Czech Trotting Association",
  "203005": "Association of Lipizzaner Breeders CZ",
  "203006": "The National Stud Kladruby nad Labem SOC",
  "203007": "Pure Bred Shagya-Arabian Society CZ",
  "203009": "Czech Warmblood Breeders Association",
  "203010": "Breeders Association of Slovak Warmblood in the Czech republic",
  "203011": "Central Register of horses",
  "203012": "The Society of Breeders and Friends of the Moravian Warmblood",
  "203013": "Association of breeders of Kinsky horses",
  "203016": "Irish Cob The Czech Republic",
  "203CZE": "Jockey Club of the Czech Republic",
  "208333": "Landscentret Heste (Danish Agricultural Advisory Service)",
  "208334": "Dansk travsports Centralforbund",
  "208335": "Graenseegnens Holstener Hesteavlsforening",
  "208336": "Dansk Selskab for Arabisk Hesteavl (Danish Arab Horse Society)",
  "208337": "Dansk Islandshesteforening",
  "208338": "Miniature Horses in Denmark",
  "208339": "Dansk Frieser Forbund",
  "208340": "Danish Connemara Pony Society",
  "208DEN": "Danish Jockey Club",
  "214DOM": "Jockey Club in Dominican Republic",
  "218001": "Associacion de Criadores de Caballos Arabes del Ecuador",
  "218ECU": "Jockay Club in Ecuador",
  "233001": "Estonian Sport Horse Breeders Society",
  "233002": "Estonian Horse Breeders Society",
  "233003": "Estonian Trotters Association",
  "233004": "Akhal-Teke Association of Estonia",
  "233005": "The Old-Tori Horse Society",
  "233006": "Estonian Native Horse Breeders Society",
  "233007": "TORI HORSE SOCIETY",
  "233999": "Unknown horses registered in Estonian horse breeding societies",
  "234001": "Fareos Icelandic Horse Association",
  "246001": "Finnish Warmblood (The Finnish breeding association) Suomen Hippos",
  "246002": "The Finnish Society for Irish Cobs",
  "246003": "Eestin Raskaat Vetohevoset ry",
  "250001": "IFCE - SIRE",
  "276307": "Hauptverband für Traberzucht und rennen eV",
  "276308": "Verband der Zuchter und Freunde des Arabischen Pferdes e.V.",
  "276309":
    "Verband der Zuchter und Freunde des Ostpreussischen Warmblutpferdes Trakehner Abstammung e.V",
  "276310": "Zuchtverband für deutsche Pferde e.V",
  "276311": "Friesenpferde-Zuchtverband eV",
  "276312": "Deutsche Quarter Horse Association e.V",
  "276313": "Zuchtverband für Sportpferde Arabischer Abstammung",
  "276316": "Lipizzaner Zuchtverband Deutschland e.V.",
  "276321": "Verband der Zuchter des Holsteiner Pferdes",
  "276322": "Pferdestammbuch Schleswig-Holstein / Hamburg e V",
  "276327": "Verband der Pferdezuchter Mecklenburg-Vorpommern e.V",
  "276330": "Zuchtverband für das Ostfriesische und Alt-Oldenburger Pferd e.V.",
  "276331": "Hannoveraner Verband e.V.",
  "276333": "Verband der Zuchter des Oldenburger Pferdes",
  "276334": "Verband der Pony-und Kleinpferdezüchter Hannover e.V",
  "276335": "Pferdestammbuch Weser-Ems e V",
  "276336": "Stammbuch für Kaltblutpferde Niedersachsen e.V",
  "276337": "Pferdezuchtverband Sachsen-Anhalt e.V",
  "276341": "Westfalisches Pferdestammbuch e.V",
  "276343": "Rheinisches Pferdestammbuch e.V",
  "276351": "Pferdezuchtverband Rheinland-Pfalz-Saar",
  "276357": "Pferdezuchtverband Brandenburg-Anhalt e.V.",
  "276361": "Verband Hessischer Pferdezüchter",
  "276363": "Verband der Pony und Pferdezüchter Hessen e.V",
  "276366": "Deutscher Pinto Zuchtverband e.V.",
  "276367": "Verband Thüringer Pferdezüchter e.V",
  "276373": "Pferdezuchtverband Baden-Württemberg e.V.",
  "276381": "Landesverband Bayerischer Pferdezüchter eV",
  "276384": "Bayerischer Zuchtverband für Kleinpferde und Spezialpferderassen e.V",
  "276387": "Pferdezuchtverband Sachsen-Thüringen e.V.",
  "276398": "Deutscher Reiterliche Vereinigung e.V.",
  "276414": "Paint Horse Club Germany e.V.",
  "276417": "European Colored Horses Association",
  "276418": "Springpferdezuchtverband Oldenburg International e.V.",
  "276455": "Pferdezuchtverband Sachsen-Thüringen",
  "276460": "European Western Horse Breeders UG",
  "276476": "Deutscher Zuchtverband fur Esen e.V.",
  "276478": "Verein der Freunde und Züchter des Berberpferdes e.V.",
  "276479": "Appaloosa Horse Club Germany e V",
  "276486": "Zuchtverband für Senner Pferde e.V.",
  "276501": "Landesverband Baden-Württemberg für Leistungsprüfungen in der Tierzucht e.V.",
  "276GER": "Deutscher Galopp e. V.",
  "300001": "Ministry of Agriculture Directorate of Inputs to Animal Production",
  "3000GR": "Jockey Club de Grèce",
  "320GTM": "Jockey Club in Guatemala",
  "340001": "Honduras Equestrian Federation",
  "348001":
    "Hungarian Sport Horse Breeders Association/Magyar Sportlótenyésztők Országos Egyesülete",
  "348003": "Gestut der Babolna Korporation/ Verband der Zuchter des arabischen Pferde Ungarn",
  "348006": "Allami Menesgazdasag Szilvasvarad",
  "348199": "Nemzeti Élelmiszerlánc-Biztonsági Hivatal (National Food Chain Safety Office)",
  "3481AH": "Akhal-Teke Breeders Association Hungary",
  "3481AR": "Society of Hungarian Arabian Horse Breeders",
  "3481AT": "Hungarian Gallop RaceHorse Breeder's Association",
  "3481AZ": "Association for Andalusian Horses in Hungary",
  "3481BD": "Hungarian Bardigiano Horse Breeding Association",
  "3481FN": "Association of Hungarian Furioso-North Star Breeders",
  "3481FZ": "Association of Friesan Horses in Hungary",
  "3481HV": "Hungarian Cold Blooded Horse Breeders Association",
  "3481IA": "Association of Hungarian Donkey Breeders",
  "3481IZ": "Hungarian Icelandic Equestrian Association",
  "3481KB": "Kisberi and Gidran Horse Breeding Association",
  "3481KN": "Konik and Primitive Horse Breeders Association",
  "3481LP": "Hungarian Lipizaner breeder's Society",
  "3481MV": "Hungarian Warmblood Breeders Association",
  "3481NO": "Hungarian Nonius Horse Association",
  "3481QH": "Hungarian Quarter Horse Association",
  "3481SD": "Hungarian Pony and Small Horse Association",
  "3481UG": "National Trotting Breeder's Association",
  "3481WH": "Hungarian Welsh and riding pony Association",
  "352001": "Landssamband Hestamanna",
  "352002": "RML Radgjafamidstod landbunadarins (The Icelandic Agricultural Advisory Centre)",
  "356IND": "Stud-book authority of India",
  "360001": "Stud Book Indonesia",
  "364001": "Equestrian Federation of the Islamic Republic of Iran-Studbook Office",
  "364002": "Caspian Conservation Society",
  "368001": "Iraqi Arabian Horse Organization",
  "372002": "Friesan Horse Society of Great Britain and Ireland Ltd",
  "372003": "The Irish Piebald & Skewbald Association Ltd t/a Leisure Horse Ireland",
  "372004": "The Connemara Pony Breeders Society",
  "372006": "Irish Cob Society",
  "372007": "The Standardbred and Trotting Horse Association of Great Britain and Ireland",
  "372009": "Irish Pony Society",
  "372010": "Irish Warmblood Stud Book Ltd",
  "372012": "Irish Appaloosa Association",
  "372013": "Irish Harness Racing Association Ltd",
  "372069": "Horse Passport Agency Ltd",
  "372414": "Horse Sport Ireland",
  "372IRE": "Weatherbys Ireland",
  "376001": "Israel Arab Horse Registry",
  "376002": "Israeli Shagya Arab Horse Society",
  "376ISR": "Israel Stud Book",
  "380001": "Associazione Italiana Allevatori",
  "380002": "Associazione Nazionale Allevatori Cavalli di Razza Haflinger",
  "380003": "Associazione Nazionale Allevatori Cavallo di Razza Maremmana",
  "380004":
    "Associazione Nazionale Allevatori del Cavallo Agricolo Italiano da Tiro Pesante Rapido",
  "380005": "Associazione Nazionale Italiana Cavallo Arabo",
  "380006": "Assoziacione Nazionale Cavallo bardigiano",
  "380007": "MIPAAF - Area Cavallo da sella",
  "380008": "MIPAAF - Area Cavallo Trottatore",
  "380009": "Instituto Incremento Ippico Della Sardegna",
  "380010": "Associazione Italiana Allevatori - Lipizzan",
  "380011": "Associazione Italiana Allevatori Unknown pedigree Horses",
  "380012": "Associazione Italiana Quarter Horse",
  "380013": "Regione Siciliana- Istituto Incremento Ippico per la Sicilia",
  "380014": "National Association of Horse Breeders of the Murge and Donkey of Martina Franca",
  "380015": "Federazione Italiana Sport Equestri",
  "380ITY": "MINISTERO DELLE POLITICHE AGRICOLE ALIMENTARI E FORESTALI",
  "392001": "Japan Association for International Racing and Stud Book",
  "398001": "Kazakh Association of Purebred Arabian Horses",
  "398002": "Republic Chamber of Horse Breeding of Kazakhstan",
  "400001": "The Royal Jordanian Stud Book Authority",
  "404KEN": "Jockey Club in Kenya",
  "410KOR": "Korea Racing Association",
  "414001": "Kuwait Arabian Horse Registry",
  "422001": "SPARCA",
  "422LBN": "SPARCA",
  "428001": "Agricultural Data Centre",
  "434001": "Libyan Arabian Horse Breeders Society",
  "434LIB": "Ministère de l'Agriculture & de la Mise en Valeur Agricole Division des Haras",
  "440001": "Lithuanian Ministry of Agriculture State Animal Breeding Supervision Service",
  "440002": "Lithuanian Trakehner Breeders' Association",
  "440003": "Zhemaitukas Breeders Association",
  "440004": "The Lithuanian Draft Horse Breeders Association",
  "440005": "Lietuvos jojamuju zirgu veisle / Lithuanian Riding Horses",
  "440006": "The Baltic Horse Breeder's Association",
  "440007": "The Republic Racing Horse League",
  "440008": "State enterprise Agricultural Data Centre",
  "440009": "Lithuanian Trotting Association",
  "440010": "The Lithuanian Horse Racing Association",
  "440011": "The National Arabian Horses Breeders Association",
  "440012": "Lithuanian equestrian association",
  "440013": "Lithuanian Heavy Draught Horse Conservation Breeders' Association",
  "442001": "Stud-book du cheval de selle luxembourgeois",
  "442002": "Stud-book Luxembourgeois du cheval de Sang",
  "442005": "Letzebuerger Ardenner Studbook",
  "442006": "Stud-book luxembourgeois pour Chevaux Haflinger",
  "442007": "Stud-book luxembourgeois pour Chevaux de taille moyenne poneys et races spéciales",
  "442008": "Ieselsfrënn Lëtzebuerg a.s.b.l.",
  "442009": "Quarter Horse Association Luxembourg",
  "442010": "CONVIS",
  "442011": "Administration des Services Techniques de l'Agriculture",
  "458MAL": "Malayan racing Association",
  "470001": "Malta Racing Club",
  "470003": "Malta Veterinary Regulation Directorate",
  "484001": "Criadores de Caballos Deportivos Mexicanos A.C",
  "484006": "Stud-book La Silla",
  "484008": "Asociacion Mexicana de Criadores de Caballos de Pura Raza Espanola",
  "484MEX": "Jockey Club Mexicano",
  "512001": "The Royal Cavalry",
  "516001": "Arab Horse Breeders Society of Namibia",
  "528001": "Arabische Volboedpaarden Stamboek in Nederland",
  "528002": "Nederlandse Quarter Horse Associatie",
  "528003": "Kon Warmbloed paardenstamboek Nederland",
  "528004": "Koninklijke Vereniging Het Friesch Paarden Stamboek",
  "528005": "Koninklijke Vereniging het Nederlands Trekpaard en De Haflinger",
  "528006": "Lipizzanerstamboek Vereniging Nederland",
  "528007": "Nederlands Mini Paarden registratie Stamboek",
  "528008": "Nederlands Rijpaarden En PonyStamboek",
  "528009": "Nederlands Sheltand Pony Stamboek",
  "528010": "Stichting nederlandse Draft- en rensport",
  "528011": "Vereiniging Nederlands Stamboek voor Islandse paarden",
  "528012": "Vereniging het Groninger Paard",
  "528013": "Vereniging het Nederlands Appaloosa Stamboek",
  "528014": "Vereniging het Nederlands Fell Pony Stamboek",
  "528015": "Vereniging het Nederlands Fjordenpaarden Stamboek",
  "528016": "Vereniging het Nederlands Hackney Stamboek",
  "528017": "Vereniging het Nederlands Welsh Pony en COB Stamboek",
  "528018": "Vereniging Nederlands New Forest Pony Stamboek",
  "528019": "Welsh Pony & Cob Vereniging",
  "528020": "Vereiniging Het Nederlands Connemara Pony Stamboek",
  "528021":
    "Vereniging Het Nederlands Stamboek voor Tinkers en Europees Moeder Stamboek voor Tinkers",
  "528022": "International Horse Breeders Association Heavy Warmblood",
  "528023": "Irish Cob Society Nederland",
  "528024": "Merens Stamboek Nederland",
  "528025": "Vereniging het Nederlands Ezelstamboek",
  "528026": "Falabella Stamboek",
  "528027": "Koninklijke Nederlandse Hippische Sportfederatie",
  "528028": "Nederlands Dartmoor Pony stamboek",
  "528029": "Vrienden van het Andalusische paard in Nederland",
  "528030": "Gypsy Cob and Drum Horse Association",
  "528031": "Europees Stamboek Amerikaanse Miniatuur Paarden",
  "528032": "Europees Arabisch Stamboek voor Shagya-paarden Sportpaarden en Sportpony`s",
  "528033": "Nederlands Haflinger Paarden Stamboek",
  "528034": "DGB BV (IKB Nederland)",
  "528035": "Klassiek Paarden Stamboek",
  "528036": "Stichting Anglo European Studbook (AES)",
  "528037": "Vereniging European Falabella Studbook",
  "528038": "De Nederlandse Shire Clydesdale en Drum Horse Vereniging",
  "528039": "Vereniging van Fokkers en Gebruikers van het Fjordenpaard",
  "540001": "UPRA Equine",
  "554001": "New Zealand Arab Horse Breeders Society Inc",
  "554002": "New Zealand Sport Horse Promotion Board Inc.",
  "554003": "Welsh Pony and Cob Society of New Zealand",
  "554004": "Trakehner Breeders Association of New Zealand",
  "554005": "Harness racing New Zealand",
  "554006": "Icelandic Horse Breeders and Riders Association New Zealand",
  "554007": "The New Zealand Hanoverian Society Incorporated",
  "554008": "Equestrian Sports New Zealand",
  "554009": "The New Zealand Warmblood Association Inc.",
  "554010": "The Connemara Pony Society of New Zealand Incorporated",
  "554011": "Sport and Performance Horse Association of New Zealand Inc.",
  "5540NZ": "New Zealand Thoroughbred Racing",
  "578001": "Det Norske Travselskap",
  "578002": "Stiftelsen Norsk Hestesenter",
  "578003": "Landslaget for Nordlanddhest/Lyngshest",
  "578004": "Norsk Ponniavlsforening",
  "578005": "Norwegian Arab Horse Society",
  "578006": "Norsk Foreining for Varmblodig Hesteavl",
  "578007": "Norsk Islandshestforening Stammbokkontoret",
  "578009": "Norsk Lipizzanerforening",
  "578011": "Norwegian Warmblood Association",
  "578012": "Norvegian Shetland Pony Society",
  "578013": "NAHF'S Shagyaavdeling",
  "578NOR": "Norsk Jockeyklub",
  "586001": "Pakistan Arabian Horse Society",
  "591001": "Arabian Horse Association",
  "591PAN": "Jockey Club in Panama",
  "600001": "Asociacion Rural del Paraguay",
  "600PRY": "Jockey Club in Paraguay",
  "604001": "Asociacion de criadores de caballo peruano de paso",
  "604PER": "Jockey club del Peru",
  "608PHI": "Stud Book Authority of the Philippines",
  "616001": "Polish Arabian Stud Book",
  "616002": "Polskie Towarzystwo Kuce Szetlandzkie (Shetland Pony)",
  "616003": "Trakehner Verband Poland",
  "616006": "Polish Horse Breeders Association",
  "616015": "Association Breeders and Users of Trotters",
  "616POL": "Polski Klub Wyscigow Konnych",
  "620001": "Direçao Geral de Alimentaçao e Veterinaria",
  "620002": "Direcçao Geral de Veterinaria",
  "620003": "Associação Portuguesa de Criadores de Cavalo Puro Sangue Lusitano",
  "634001": "Qatar Arabian Horse Registry Race & Equestrian Club",
  "634002": "Qatar Horse Registry",
  "643001": "The Russian Arabian Stud Book Office",
  "643003": "Assoziation d. Trakehner Pferde-Gestüte Russlands",
  "643004": "CIS Trotting Association",
  "643005": "State Studbook of Russian Riding Horse",
  "643RUS": "All Russian Research Institute for Horsebreeding",
  "682001": "King Abdul Aziz Arabian Horse centre",
  "682SDA": "Saudi Arabian stud book",
  "688001": "Ministry of Agriculture Forestry and Water management",
  "688002": "Serbian Association for Purebred Arabian Horses",
  "703001": "Narodny Zrebcin Topolcianky",
  "703002": "Slovak Horse Breeding society/Zväz chovatelov koni na Slovensku-druzstvo",
  "703003": "Statny Zrecin",
  "703005": "Nationalgestut Topolcianky",
  "703SVK": "Turf DirektoriuM Bratislava",
  "705001":
    "UL Veterinarska fakulteta Klinika za reprodukcijo in velike zivali - Stud Book for Slovenian Warmblood Horses",
  "705002": "Haras de Lipica",
  "710001": "South African Warmblood Horse Society",
  "710002": "The Arab Horse Society of South Africa",
  "710003": "Welsh Pony and Cob Society of South Africa",
  "710004": "South Africa Lipizzaners",
  "710005": "Trotting South Africa (TSA)",
  "710SAF": "The National Horseracing Authority",
  "716001": "Arab Horse Society of Zimbabwe",
  "724001": "Federacion nacional de trote",
  "724002": "Asociacion de Criadores de Pura Sangre Inglés de Espana",
  "724003": "Direccion General. Produccion Agropecuaria",
  "724004":
    "Asociación de criadores de la raza Burguete de Navarra y Asociación de Criadores de Jaca Navarra",
  "724006": "Asociacion de Criadores de Ponis de Raza Asturcon",
  "724007": "Asociacion de Criadores de Cabalo de Pura Raza Galega",
  "724008": "Consejeria de Ganaderia Agricuctura y Pesca",
  "724009": "EPOFE (Euskal Pottokazaleen Federazioa)",
  "724010": "Servicio de Produccion Ganadera",
  "724011": "Asociacion para el fomento de la raza Asnal Catalana",
  "724012": "Agricultura y Pesca Servicio de Ganaderia",
  "724013": "Grupo de Conservacion y Fomento Burro Majorero",
  "724014": "Asociacion Nacional Criadores de Ganado raza asnal Zamorano-Leonesa",
  "724015": "Asociacion Nacional de Criadores de Caballos de Pura Raza Española",
  "724016": "ANCADES asociacion nacional del caballo de deporte espanol",
  "724017": "Asociación Española de Criadores de Caballos Anglo-árabes / Spanish Anglo-Arabian",
  "724018": "Union Espanola de Ganaderos de Caballos de Pura Raza Hispano-arabe",
  "724019": "Asociacion de Criadores y Propietarios de Caballos de Raza Mallorquina",
  "724020": "Asociacion de Criadores y Propietarios de Caballos de Raza Menorquina",
  "724021": "Asociacion de Criadores y Propietarios de Caballos Trotadores",
  "724022": "Asociacion Espanola de Criadores de Caballos Arabes",
  "724023":
    'Asociación de Criadores de Ganado Equino de la raza Hispano Bretona en Cantabria "Manadas"',
  "724024": "Unión de Ganaderos de la Raza Asnal Andaluza",
  "724025": "Federacio d'Asociacions de Criadors del Cavall Pirinenc Català",
  "724026": "Asociacion Nacional de Criadores de Ganado Marismeno",
  "724027": 'Asociación de Criadores de Caballos Losinos "El Bardojal"',
  "724028": "Asociación del Asno de Pura Raza Andaluza",
  "724029": "Asociación de Criadores de Pura Raza Caballo de las Retuertas",
  "724901":
    "Organismo emisor de Documento de Identificacion de Equidos de crianza y renta en la Comunidad Autonoma de Andalucia",
  "724902":
    "Organismo emisor de Documento de Identificacion de Equidos de crianza y renta en la Communidad Autonoma de Aragon",
  "724903": "Consejeria de Medio Rural y Pesca des Principado de Asturias",
  "724904":
    "Organismo emisor de Documento de Identificacion de Équidos de crianza y renta en la Comunidad Autonoma de las Illes Balears",
  "724906":
    "Organismo emisor de Documento de Identificación de Équidos de crianza y renta en la Comunidad Autónoma de Cantabria",
  "724907":
    "Organismo emisor de Documento de Identificación de Équidos de crianza y renta en la Comunidad Autónoma de Castilla-La Mancha",
  "724908":
    "Organismo emisor de Documento de Identificacion de Équidos de crianza y renta en la Comunidad de Castilla y Leon",
  "724909": "Departament d'Accio Climatica Alimentacio i Agenda Rural",
  "724910":
    "Organismo emisor de Documento de Identificación de Équidos de crianza y renta en la Comunidad Autónoma de Extremadura",
  "724911":
    "Organismo emisor de Documento de Identificación de Équidos de crianza y renta en la Comunidad Autónoma de Galicia",
  "724912":
    "Organismo emisor de Documento de Identificación de Équidos de crianza y renta en la Comunidad de Madrid",
  "724913":
    "Organismo emisor de Documento de Identificacion de Equidos de crianza y renta en la Comunidad Autonoma de la Region de Murcia",
  "724914":
    "Organismo emisor de Documento de Identificación de Équidos de crianza y renta en la Comunidad Foral de Navarra",
  "724915":
    "Organismo emisor de Documento de Identificacion de Équidos de crianza y renta en la Comunidad Autonoma del Pais Vasco o Euskadi",
  "724916":
    "Organismo emisor de Documento de Identificación de Équidos de crianza y renta en la Comunidad Autónoma de La Rioja",
  "724917":
    "Organismo emisor de Documento de Identificación de Équidos de crianza y renta en la Comunidad Valenciana",
  "724918":
    "Organismo emisor de Documento de Identificacion de Équidos de crianza y renta en la Ciudad de Ceuta",
  "724919":
    "Organismo emisor de Documento de Identificacion de Équidos de crianza y renta en la Ciudad de Melilla",
  "752001": "Svenska Hästavelsförbundet SH",
  "752002": "Svenska Travsportens Centralförbund (STC)",
  "752003": "Swedish Arab Horse registry",
  "752004": "Swedish Warmblood Association",
  "752005": "Svenska Poitou Föreningen",
  "752006": "Sveriges Shetlandssällskap",
  "752007": "Svenska Morganhästföreningen",
  "752008": "Svenska Lusitanosällskapet",
  "752012": "Svenska Quarterhästföreningen",
  "752013": "Svenska Painthästföreningen",
  "752014": "Svenska Shagya-arabföreningen",
  "752015": "Svenska Knabstrupperföreningen",
  "752016": "Svenska Appaloosaföreningen",
  "752017": "Svenska Achaltekeerföreningen",
  "752018": "Svenska Frieserhästföreningen",
  "752019": "Svenska American Curlyhorse-föreningen",
  "752020": "Svenska Basjkirhästföreningen",
  "752022": "Föreningen Nordsvenska Hästen",
  "752023": "Avelsföreningen For Svenska Ardennerhästen",
  "752024": "Svenska Fjordhästföreningen",
  "752025": "Svenska föreningen för Irish Cob",
  "752026": "Gypsy Cob Society Sweden",
  "752029": "Svenska Shirehästföreningen",
  "752030": "Svenska Russavelsföreningen",
  "752031": "Svenska Islandshästförbundets Stiftelse för Avel SIF Avel",
  "752032": "Svenska Haflingerföreningen",
  "752033": "Svenska Connemarasällskapet",
  "752034": "Svenska New Forestföreningen",
  "752035": "Svenska Welshponny- och Cobföreningen",
  "752040": "Svenska Dartmoorsällskapet",
  "752041": "Svenska Exmooravelsföreningen",
  "752043": "Avelsföreningen för Svensk Ridponny",
  "752044": "Rid- och Sportponnyföreningen",
  "752045": "Svenska Åsneföreningen",
  "752046": "Swedish Caspian Horse Association",
  "752047": "Svensk Tyroler-Haflingeravel",
  "752048": "Svenska Avelsorganisationen för Amerikanska HästRaser",
  "752082": "Svenska Föreningen för Edelbluthaflinger",
  "752101": "Svenska Saddlebredföreningen",
  "752103": "Svenska Angloarabföreningen",
  "752106": "Svenska Lipizzanerföreningen",
  "752SWE": "Svensk Galopp",
  "756001": "Schweizer Zuchtgenossenschaft für Arabische Pferde",
  "756002": "Suisse Trot",
  "756003": "Zuchtverband Des CH - Warmblut-Sportpferdes",
  "756004": "Islandpferdevereinigung Schweiz IPV CH",
  "756005": "Schweizerischer Verband für Ponys und Kleinpferde",
  "756007": "Association Suisse du Cheval Barbe",
  "756009": "Arbertsgemeinschaft Haflinger Schweiz",
  "756010": "Shagya Araberverband der Schweiz",
  "756011": "Zuchtverband Arabische Mischrassen",
  "756012": "Fédération Suisse des Sports Equestres",
  "756013": "Fédération suisse du Franche-Montagne",
  "756014":
    "Fédération suisse du Franche-Montagne - mulets/ Schweizerischer Freibergerzuchtverband",
  "756015": "Verein Special Color Schweiz",
  "756016": "Haflinger Dachorganisation Haflinger-Pentagon Sàrl-GmbH",
  "756017": "Suisse Sport- und Reitpferde Suisse chevaux de sport et de selle",
  "756100": "Galopp Schweiz",
  "756SWI": "Tierverkehrsdatenbank Banque de Données sur le Trafic des Animaux",
  "760001": "Ministry of Agriculture & Agrarian Reform (MAAR)",
  "764THA": "Stud-book authority of Thailand",
  "780TRI": "Thoroughbreds in Trinidad et Tobago",
  "784001": "Emirates Arabian Horse Society",
  "784002": "Emirates Equestrian Federation",
  "784UAE": "Emirates Racing Association",
  "788001": "Fondation Nationale d'Amelioration de la Race Chevaline",
  "792001": "Turkish Arabian Horse registry",
  "792TUR": "Turkish Thoroughbred Stud Book",
  "804001": "Agency on identification and registration of animals",
  "804002": "Ukrainian Horse Breeders Associaton",
  "804003": "OWNER'S TROTTING ASSOCIATION",
  "818001": "Egyptian Agricultural Organization Arabian Horse Breeding Administration",
  "826002": "Anglo European Studbook",
  "826003": "British Association for the Purebred Spanish Horse",
  "826004": "The British Horse Society",
  "826005": "British Appaloosa Society",
  "826006": "British Hanoverian Horse Society",
  "826007": "British Horse Database",
  "826008": "British miniature Horse Society",
  "826009": "British Morgan Horse Society",
  "826010": "British Palomino Horse Society",
  "826011": "British Percheron Horse Society",
  "826012": "American Quarter Horse Association UK",
  "826013": "British Skewbald & Piebald Association",
  "826014": "British Sport Horse Registry",
  "826015": "British Spotted Pony Society",
  "826016": "Warmblood Breeders Studbook UK",
  "826017": "Caspian Horse Society",
  "826018": "Cleveland Bay Horse Society",
  "826020": "Dales Pony Society",
  "826021": "Dartmoor Pony Society",
  "826022": "Donkey Breed Society",
  "826023": "English Connemara Pony Society",
  "826024": "Eriskay Pony Society",
  "826025": "Exmoor Pony Society",
  "826026": "Spotted Pony Breed Society (Great Britain)",
  "826027": "Fell Pony Society",
  "826028": "Fjord Horse National Stud Book Association of Great Britain",
  "826030": "Hackney Horse Society",
  "826031": "Highland Pony Society",
  "826032": "Icelandic Horse Society of Great Britain",
  "826033": "International miniature Horse and Pony Society",
  "826034": "Irish Draught Horse Society",
  "826035": "Lipizzaner national stud book association of Great Britain",
  "826037": "National Pony Society",
  "826038": "New Forest Pony Breeding & Cattle Society",
  "826039": "Shetland Pony Stud-book Society",
  "826040": "Shire Horse Society",
  "826041": "Sport Horse Breeding of Great Britain",
  "826042": "Spotted Horse and Pony Society",
  "826043": "Suffolk Horse Society",
  "826044": "Arab Horse Society",
  "826045": "Trakehner Breeders Fraternity",
  "826046": "Welsh Pony & Cob Society",
  "826047": "Scottish Sport Horse",
  "826049": "British Driving Society",
  "826050": "British Harness Racing Club",
  "826051": "British Equestrian federation",
  "826052": "Hurlingham Polo Association",
  "826053": "Caspian Breed Society (UK)",
  "826054": "Coloured Horse and Pony Society UK",
  "826055": "Scottish Icelandic Horse Association",
  "826057": "British Bavarian Warmblood Association",
  "826058": "Appaloosa Horse Club UK",
  "826059": "Fjord Horse registry of Scotland and Fjord Horse UK",
  "826060": "The Sports Pony Studbook Society",
  "826061": "Comann Each nan Eilean - The Eriskay Pony (Purebred) Studbook Society",
  "826063": "The American Saddlebred Association of Great Britain",
  "826064": "British Show Jumping Association",
  "826065": "The Haflinger Society of Great Britain",
  "826066": "The Miniature Mediterranean Donkey Association",
  "826067": "Horse Passport Agency Ltd",
  "826068": "The Gypsy Cob Society Ltd",
  "826069": "Horse Passport Agency Ltd",
  "826070": "The Lipizzaner Society of GB",
  "826071": "The United Saddlebred Association UK",
  "826072": "The Clydesdale Horse Society",
  "826073": "Pet ID Equine",
  "826074": "Horse Passports Ltd",
  "826075": "Veteran Horse Society",
  "826076": "Farmkey Genus Breeding Ltd",
  "826077": "Selle Francais/EquiCours",
  "826078": "American Miniature Horse Club GB",
  "826079": "British Falabella Studbook",
  "826080": "British Camargue Horse Society",
  "826081": "Lusitano Breed Society of Great Britain",
  "826082": "The Showjumping Association of Ireland - Ulster Region",
  "826083": "Oakdale (NI) Ltd",
  "826084": "British Show Hack Cob & Riding Horse Association",
  "826087": "UK Knabstrupper Association",
  "826088": "Breeders Elite Studbook for Irish and European Sporthorses Ltd",
  "826089": "The Traditional Gypsy Cob Association Limited",
  "826090": "Northern Ireland Horse Board",
  "826091": "FRIESIAN HORSE UK LTD",
  "8260GB": "Weatherbys",
  "840001": "American Bucksin Registry Association",
  "840002": "American Hackney Horse Society",
  "840003": "American Holsteiner Horse Association",
  "840004": "American Miniature Horse Association",
  "840005": "American Paint Horse Association",
  "840006": "American Quarter Horse Association",
  "840007": "American Trakehner Association Inc",
  "840008": "American Warmblood Registry",
  "840009": "American Warmblood Society",
  "840010": "American White/american Creme Horse registry",
  "840011": "Appaloosa Horse Club",
  "840013": "Belgian Warmblood Breeding Association",
  "840014": "International Bucksin Horse Association INC",
  "840015": "Performance Horse Registry",
  "840016": "Oldenburg Horse Breeders Society",
  "840017": "International Sporthorse Registry/ Oldenburg Registry NA",
  "840018": "Palomino Horse Breeders of America INC",
  "840019": "Peruvian Paso Horse Registry of North America",
  "840020": "Pinto Horse Association of America INC",
  "840021": "Pony of the Americas Club INC",
  "840022": "Swedish Warmblod Association of North America",
  "840023": "The American Hanoverian Society",
  "840024": "The American Morgan Horse Association",
  "840025": "KWPN of North America",
  "840026": "The Purebred Arabian Horse Registry",
  "840027": "The United States Trotting Association",
  "840028": "Welsh Pony and Cob Society of America",
  "840029": "Norwegian Fjord Horse Registry",
  "840030": "North American Shagya Society",
  "840031": "International Sport Pony Registry",
  "840032": "Lipizzan Association of America",
  "840033": "Irish Draught Horse Society of North America",
  "840034": "International Jumper Futurity Studbook",
  "840035": "International Curly Horse Organization",
  "840036": "Nokota Horse Conservancy",
  "840037": "Friesian Horse Society",
  "840038": "Continental Stud Book",
  "840039": "Friesian Sporthorse Association",
  "840040": "Foundation for the Pure Spanish Horse",
  "840041": "American Heritage Horse Association",
  "840042": "Spanish Mustang Registry Inc.",
  "840043": "California Vaquero Horse Association",
  "840044": "United States Icelandic Horse Congress",
  "840045": "Horse of the Americas Registry",
  "840046": "The Akhal-Teke Horse Registry",
  "840047": "North American Studbook",
  "840048": "United States Lipizzan Federation",
  "840049": "Trakehner Association of North America",
  "840052": "United States Lusitano Association",
  "858001": "Asociacion rural del Uruguay",
  "858002": "Sociedad Criadores de Caballos Arabes",
  "858003": "Stud Book Uruguayo",
  "860UZB": "the Equestrian Federation of Uzbekistan",
  "862001": "Asociacion Venezolana De Criadores De Caballos Arabes",
  "862VEN": "Jockey Club in Venezuela",
  "887001":
    "General Federation for Equestrian & Camel Racing Registration Centre of Pure Arabian Horses of Yemen",
  FEIFEI: "Federation Equestre Internationale",
  SVN001: "Slovenian Turf Club",
};

/** A APSL, que é quem gere o Livro Genealógico do Puro Sangue Lusitano. */
export const CODIGO_APSL = "620003";
