/* GERADO — não editar à mão.
 *
 * Fonte: `dados/oficiais/passaporte-anexo-ii.csv`, transcrito do Anexo II do
 * Regulamento de Execução (UE) 2021/963. Para mudar, edita-se o CSV e corre-se
 * `npm run oficiais:gerar`. */

/**
 * O que um passaporte equino da União imprime, campo a campo.
 *
 * O leitor de documentos procurava rótulos **inferidos do que esses documentos
 * costumam imprimir**, e isso estava escrito no código como o ponto mais fraco
 * de todo o sistema de verificação. Estes vêm do regulamento.
 *
 * O `fr` é `null` nas linhas da Secção V: essa secção é o certificado
 * zootécnico e não aparece nas três línguas no mesmo documento.
 */
export interface RotuloDoPassaporte {
  /** O que o campo é, em português corrente. Não é o que vem impresso. */
  campo: string;
  fr: string | null;
  en: string;
  pt: string;
  /** Onde no Anexo II, para se poder ir confirmar. */
  seccao: string;
}

export const ROTULOS_DO_PASSAPORTE: readonly RotuloDoPassaporte[] = [
  {
    campo: "Espécie",
    fr: "Espèce:",
    en: "Species:",
    pt: "Espécie:",
    seccao: "Secção I, Parte A, item (1)(a)",
  },
  {
    campo: "Sexo",
    fr: "Sexe:",
    en: "Sex:",
    pt: "Sexo:",
    seccao: "Secção I, Parte A, item (1)(b)",
  },
  {
    campo: "Data de nascimento",
    fr: "Date de naissance:",
    en: "Date of birth:",
    pt: "Data de nascimento:",
    seccao: "Secção I, Parte A, item (2)(a)",
  },
  {
    campo: "Local e país de nascimento",
    fr: "Lieu et pays de naissance:",
    en: "Place and country of birth:",
    pt: "Local e país de nascimento:",
    seccao: "Secção I, Parte A, item (2)(b)",
  },
  {
    campo: "Nome do animal",
    fr: "Nom (optionnel):",
    en: "Name (optional):",
    pt: "Nome (facultativo)",
    seccao: "Secção I, Parte A, item (2)(c)",
  },
  {
    campo: "Descritivo (cabeçalho)",
    fr: "Signalement:",
    en: "Description:",
    pt: "Descritivo:",
    seccao: "Secção I, Parte A, item (3)",
  },
  {
    campo: "Pelagem",
    fr: "Robe:",
    en: "Colour:",
    pt: "Pelagem:",
    seccao: "Secção I, Parte A, item (3)(a)",
  },
  {
    campo: "Cabeça",
    fr: "Tête:",
    en: "Head:",
    pt: "Cabeça:",
    seccao: "Secção I, Parte A, item (3)(b)",
  },
  {
    campo: "Membro anterior esquerdo",
    fr: "Ant. G:",
    en: "Foreleg L:",
    pt: "Ant. Esq.:",
    seccao: "Secção I, Parte A, item (3)(c)",
  },
  {
    campo: "Membro anterior direito",
    fr: "Ant. D:",
    en: "Foreleg R:",
    pt: "Ant. Dir.:",
    seccao: "Secção I, Parte A, item (3)(d)",
  },
  {
    campo: "Membro posterior esquerdo",
    fr: "Post G:",
    en: "Hind leg L:",
    pt: "Post. Esq.:",
    seccao: "Secção I, Parte A, item (3)(e)",
  },
  {
    campo: "Membro posterior direito",
    fr: "Post D:",
    en: "Hind leg R:",
    pt: "Post. Dir.:",
    seccao: "Secção I, Parte A, item (3)(f)",
  },
  {
    campo: "Corpo",
    fr: "Corps:",
    en: "Body:",
    pt: "Corpo:",
    seccao: "Secção I, Parte A, item (3)(g)",
  },
  {
    campo: "Marcas",
    fr: "Marques:",
    en: "Markings:",
    pt: "Marcas:",
    seccao: "Secção I, Parte A, item (3)(h)",
  },
  {
    campo: "UELN / código único",
    fr: "Code Unique ou Numéro unique d'identification valable à vie (15 chiffres):",
    en: "Unique Code or lifer number: (15 digits):",
    pt: "Código único ou Número único vitalício (15 dígitos):",
    seccao: "Secção I, Parte A, item (4)",
  },
  {
    campo: "Código de barras",
    fr: "Code-barres (optionnel)",
    en: "Bar-Code (optional)",
    pt: "Código de barras (facultativo)",
    seccao: "Secção I, Parte A, itens (4) e (5)",
  },
  {
    campo: "Transponder / microchip",
    fr: "Code du transpondeur (si disponible)",
    en: "Transponder code (where available)",
    pt: "Código do transpondedor (se disponível)",
    seccao: "Secção I, Parte A, item (5)",
  },
  {
    campo: "Sistema de leitura do transponder",
    fr: "Système de lecture (si différent de ISO 11784)",
    en: "Reading system (if not ISO 11784)",
    pt: "Sistema de leitura (se não for ISO 11784)",
    seccao: "Secção I, Parte A, item (5)",
  },
  {
    campo: "Método alternativo de identificação",
    fr: "Méthode alternative de vérification d'identité (si applicable)",
    en: "Alternative method for identity verification (if applicable)",
    pt: "Método alternativo de verificação da identidade (se aplicável)",
    seccao: "Secção I, Parte A, item (6)",
  },
  {
    campo: "Grupo sanguíneo / ADN",
    fr: "Information sur toute autre méthode appropriée donnant des garanties pour vérifier l'identité de l'animal (groupe sanguin/code ADN) (optionnel)",
    en: "Information on any other appropriate method providing guarantees to verify the identity of the animal (blood group/DNA code) (optional)",
    pt: "Informações sobre qualquer outro método adequado que ofereça garantias na verificação da identidade do animal (grupo sanguíneo/código ADN) (facultativo)",
    seccao: "Secção I, Parte A, item (7)",
  },
  {
    campo: "Data (da identificação)",
    fr: "Date",
    en: "Date",
    pt: "Data",
    seccao: "Secção I, Parte A, item (8)",
  },
  {
    campo: "Local (da identificação)",
    fr: "Lieu",
    en: "Place",
    pt: "Local",
    seccao: "Secção I, Parte A, item (9)",
  },
  {
    campo: "Assinatura da pessoa qualificada",
    fr: "Signature de la personne qualifiée (nom en lettres capitales)",
    en: "Signature of qualified person (name in capital letters)",
    pt: "Assinatura da pessoa qualificada (nome em maiúsculas)",
    seccao: "Secção I, Parte A, item (10)",
  },
  {
    campo: "Carimbo da autoridade",
    fr: "Cachet de l'autorité compétente ou de l'organisme délégué",
    en: "stamp of competent authority or delegated body",
    pt: "Carimbo da autoridade competente ou do organismo delegado",
    seccao: "Secção I, Parte A",
  },
  {
    campo: "Resenho gráfico (título da parte)",
    fr: "Partie B – Signalement graphique",
    en: "Part B – Outline Diagram",
    pt: "Parte B – Resenho gráfico",
    seccao: "Secção I, Parte B",
  },
  {
    campo: "Castração / alterações (título da parte)",
    fr: "Partie C – Castration, vérification de la description, autres modifications",
    en: "Part C – Castration, verification of the description, other modifications",
    pt: "Parte C – Castração, verificação do descritivo, outras alterações",
    seccao: "Secção I, Parte C",
  },
  {
    campo: "Castração",
    fr: "Castration",
    en: "Castration",
    pt: "Castração",
    seccao: "Secção I, Parte C",
  },
  {
    campo: "Identificação",
    fr: "Identification",
    en: "Identification",
    pt: "Identificação",
    seccao: "Secção I, Parte C",
  },
  {
    campo: "Data e local da castração",
    fr: "Date et lieu de la castration",
    en: "Date and place of castration",
    pt: "Data e local da castração",
    seccao: "Secção I, Parte C",
  },
  {
    campo: "Verificação do descritivo",
    fr: "Vérification de la description",
    en: "Verification of the description",
    pt: "Verificação do descritivo",
    seccao: "Secção I, Parte C",
  },
  {
    campo: "Alterações",
    fr: "Rectifications",
    en: "Amendments",
    pt: "Alterações",
    seccao: "Secção I, Parte C, item 1",
  },
  {
    campo: "Aditamentos",
    fr: "Adjonctions",
    en: "Additions",
    pt: "Aditamentos",
    seccao: "Secção I, Parte C, item 2",
  },
  {
    campo: "Registo noutra base de dados",
    fr: "Enregistrement d'un document d'identification dans la base de données d'un autorité compétente ou d'un organisme délégué autre que celui qui a délivré le document original",
    en: "Registration of an identification document in the database of a competent authority or delegated body other than that which issued the original document",
    pt: "Registo de um documento de identificação na base de dados de uma autoridade competente ou de um organismo delegado que não seja o que emitiu o documento original",
    seccao: "Secção I, Parte C, item 3",
  },
  {
    campo: "Código único (repetido no topo das secções)",
    fr: "Code Unique",
    en: "Unique Code",
    pt: "Código Único",
    seccao: "Secções I(C), II, III, IV",
  },
  {
    campo: "Administração de medicamentos (título)",
    fr: "Administration de médicaments",
    en: "Administration of medicinal products",
    pt: "Administração de medicamentos",
    seccao: "Secção II",
  },
  {
    campo: "Marca de validação / licença (título)",
    fr: "Marque de validation ou licence",
    en: "Validation Mark or Licence",
    pt: "Marca de validação ou licença",
    seccao: "Secção III",
  },
  {
    campo: "Marca de validação válida até",
    fr: "Marque de validation valable jusque à",
    en: "Validation mark valid until",
    pt: "Marca de validação válida até",
    seccao: "Secção III",
  },
  {
    campo: "Licença válida até",
    fr: "Licence valable jusque à",
    en: "Licence valid until",
    pt: "Licença válida até",
    seccao: "Secção III",
  },
  {
    campo: "Autoridade competente ou organismo delegado",
    fr: "Autorité compétente ou organisme délégué",
    en: "Competent authority or delegated body",
    pt: "Autoridade competente ou organismo delegado",
    seccao: "Secção III",
  },
  {
    campo: "Dados do proprietário (título)",
    fr: "Coordonnées du propriétaire",
    en: "Details of ownership",
    pt: "Dados relativos ao proprietário",
    seccao: "Secção IV",
  },
  {
    campo: "Data de registo pela organização",
    fr: "Date d'enregistrement par l'organisation, l'association ou le service officiel",
    en: "Date of registration by the organisation, association, or official service",
    pt: "Data de registo pela organização, associação ou serviço oficial",
    seccao: "Secção IV",
  },
  {
    campo: "Nome do proprietário",
    fr: "Nom du propriétaire",
    en: "Name of owner",
    pt: "Nome do proprietário",
    seccao: "Secção IV",
  },
  {
    campo: "Endereço do proprietário",
    fr: "Adresse du propriétaire",
    en: "Address of owner",
    pt: "Endereço do proprietário",
    seccao: "Secção IV",
  },
  {
    campo: "Nacionalidade do proprietário",
    fr: "Nationalité du propriétaire",
    en: "Nationality of owner",
    pt: "Nacionalidade do proprietário",
    seccao: "Secção IV",
  },
  {
    campo: "Assinatura do proprietário",
    fr: "Signature du propriétaire",
    en: "Signature of owner",
    pt: "Assinatura do proprietário",
    seccao: "Secção IV",
  },
  {
    campo: "Carimbo da organização e assinatura",
    fr: "Cachet de l'organisation, association ou service officiel et signature",
    en: "Organisation, association or official service stamp and signature",
    pt: "Carimbo da organização, associação ou serviço oficial e assinatura",
    seccao: "Secção IV",
  },
  {
    campo: "Associação de criadores emissora",
    fr: null,
    en: "Name of issuing breed society or competent authority",
    pt: "Nome da associação de criadores ou da autoridade competente emissora",
    seccao: "Secção V, Parte I, item 1",
  },
  {
    campo: "Nome no livro genealógico",
    fr: null,
    en: "Name of breeding book",
    pt: "Nome no livro genealógico",
    seccao: "Secção V, Parte I, item 2",
  },
  {
    campo: "Nome da raça",
    fr: null,
    en: "Name of breed",
    pt: "Nome da raça",
    seccao: "Secção V, Parte I, item 3",
  },
  {
    campo: "Nome do animal e país de nascimento",
    fr: null,
    en: "Name and commercial name of animal and code of country of birth",
    pt: "Nome e nome comercial do animal e código do país de nascimento",
    seccao: "Secção V, Parte I, item 4",
  },
  {
    campo: "Número de identificação individual",
    fr: null,
    en: "Individual identification number",
    pt: "Número de identificação individual",
    seccao: "Secção V, Parte I, item 5.1",
  },
  {
    campo: "Número único vitalício (UELN)",
    fr: null,
    en: "Unique Life Number",
    pt: "Número único vitalício",
    seccao: "Secção V, Parte I, item 5.2",
  },
  {
    campo: "Número no livro genealógico",
    fr: null,
    en: "Breeding book number",
    pt: "Número no livro genealógico",
    seccao: "Secção V, Parte I, item 6",
  },
  {
    campo: "Identificação do animal",
    fr: null,
    en: "Identification of animal",
    pt: "Identificação do animal",
    seccao: "Secção V, Parte I, item 7",
  },
  {
    campo: "Código do transpondedor",
    fr: null,
    en: "Transponder code",
    pt: "Código do transpondedor",
    seccao: "Secção V, Parte I, item 7.1",
  },
  {
    campo: "Sistema de leitura",
    fr: null,
    en: "Reading system (if not ISO 11784)",
    pt: "Sistema de leitura (se não for ISO 11784)",
    seccao: "Secção V, Parte I, item 7.1",
  },
  {
    campo: "Código de barras",
    fr: null,
    en: "Bar-Code",
    pt: "Código de barras",
    seccao: "Secção V, Parte I, item 7.1",
  },
  {
    campo: "Método alternativo de verificação",
    fr: null,
    en: "Alternative method for identity verification",
    pt: "Método alternativo para verificação da identidade",
    seccao: "Secção V, Parte I, item 7.2",
  },
  {
    campo: "Data de nascimento",
    fr: null,
    en: "Date of birth of animal (use format dd/mm/yyyy)",
    pt: "Data de nascimento do animal (utilizar o formato dd/mm/aaaa)",
    seccao: "Secção V, Parte I, item 8",
  },
  {
    campo: "País de nascimento",
    fr: null,
    en: "Country of birth of animal",
    pt: "País de nascimento do animal",
    seccao: "Secção V, Parte I, item 9",
  },
  {
    campo: "Criador",
    fr: null,
    en: "Name, address and email address of breeder",
    pt: "Nome, endereço e correio eletrónico do criador",
    seccao: "Secção V, Parte I, item 10",
  },
  {
    campo: "Genealogia",
    fr: null,
    en: "Pedigree",
    pt: "Genealogia",
    seccao: "Secção V, Parte I, item 11",
  },
  {
    campo: "Pai",
    fr: null,
    en: "Sire — Breeding book number and section",
    pt: "Pai — Número e secção no livro genealógico",
    seccao: "Secção V, Parte I, item 11.1",
  },
  {
    campo: "Mãe",
    fr: null,
    en: "Dam — Breeding book number and section",
    pt: "Mãe — Número e secção no livro genealógico",
    seccao: "Secção V, Parte I, item 11.2",
  },
];
